In [1]:
import geopandas as gpd
import numpy as np
import pandas as pd

In [11]:
gdf=gpd.read_file('NYC_Taxi_Zones.geojson')
gdf['centroid'] = gdf.geometry.centroid
gdf['centroid_wkt'] = gdf['centroid'].to_wkt()
gdf = gdf.drop(columns=['centroid'])
gdf

C:\Users\ShiRo\AppData\Local\Temp\ipykernel_25316\3781268433.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf['centroid'] = gdf.geometry.centroid

,shape_area,objectid,shape_leng,location_id,zone,borough,geometry,centroid_wkt
0,0.0007823067885,1,0.116357453189,1,Newark Airport,EWR,"MULTIPOLYGON (((-74.18445 40.69500, -74.18449 ...",POINT (-74.174 40.691831)
1,0.00486634037837,2,0.43346966679,2,Jamaica Bay,Queens,"MULTIPOLYGON (((-73.82338 40.63899, -73.82277 ...",POINT (-73.831299 40.616745)
2,0.000314414156821,3,0.0843411059012,3,Allerton/Pelham Gardens,Bronx,"MULTIPOLYGON (((-73.84793 40.87134, -73.84725 ...",POINT (-73.847422 40.864474)
3,0.000111871946192,4,0.0435665270921,4,Alphabet City,Manhattan,"MULTIPOLYGON (((-73.97177 40.72582, -73.97179 ...",POINT (-73.976968 40.723752)
4,0.000497957489363,5,0.0921464898574,5,Arden Heights,Staten Island,"MULTIPOLYGON (((-74.17422 40.56257, -74.17349 ...",POINT (-74.188484 40.552659)
...,...,...,...,...,...,...,...,...
258,0.000168611097013,256,0.0679149669603,256,Williamsburg (South Side),Brooklyn,"MULTIPOLYGON (((-73.95834 40.71331, -73.95681 ...",POINT (-73.959905 40.71088)
259,0.000394552487366,259,0.126750305191,259,Woodlawn/Wakefield,Bronx,"MULTIPOLYGON (((-73.85107 40.91037, -73.85207 ...",POINT (-73.852215 40.897932)
260,0.000422345326907,260,0.133514154636,260,Woodside,Queens,"MULTIPOLYGON (((-73.90175 40.76078, -73.90147 ...",POINT (-73.906306 40.744235)
261,0.0000343423231652,261,0.0271204563616,261,World Trade Center,Manhattan,"MULTIPOLYGON (((-74.01333 40.70503, -74.01327 ...",POINT (-74.013023 40.709139)
262,0.000122330270966,262,0.0490636231541,262,Yorkville East,Manhattan,"MULTIPOLYGON (((-73.94383 40.78286, -73.94376 ...",POINT (-73.94651 40.775932)

In [12]:
total_regions = len(gdf)
gdf['population_exchange'] = None
gdf['average_fee'] = None

#以下是一个人口交换的随机表

location_ids = [str(i) for i in range(1, total_regions + 1)]

exchange_matrix = pd.DataFrame(index=location_ids, columns=location_ids, data=np.random.randint(-100, 100, (total_regions, total_regions)))
for i in range(total_regions):
    for j in range(i + 1, total_regions):
        exchange_matrix.iloc[j, i] = -exchange_matrix.iloc[i, j]


average_fee_list = np.random.uniform(10, 20, size=total_regions)

for index, row in gdf.iterrows():
    loc_id = row['location_id']
    if loc_id in location_ids:
        # 由于location_ids是字符串数组，我们可以直接使用它来索引exchange_matrix
        gdf.at[index, 'population_exchange'] = exchange_matrix.loc[loc_id, :].tolist()
        # 对于averageFee，我们需要从location_ids中找到当前loc_id的索引，然后使用这个索引从average_fee_list中获取值
        idx = location_ids.index(loc_id)
        gdf.at[index, 'average_fee'] = average_fee_list[idx]

gdf['population_exchange'] = gdf['population_exchange'].apply(lambda x: str(x))

gdf

,shape_area,objectid,shape_leng,location_id,zone,borough,geometry,centroid_wkt,population_exchange,average_fee
0,0.0007823067885,1,0.116357453189,1,Newark Airport,EWR,"MULTIPOLYGON (((-74.18445 40.69500, -74.18449 ...",POINT (-74.174 40.691831),"[49, -32, 55, -18, 90, -70, -44, 3, -97, 0, 20...",14.709312
1,0.00486634037837,2,0.43346966679,2,Jamaica Bay,Queens,"MULTIPOLYGON (((-73.82338 40.63899, -73.82277 ...",POINT (-73.831299 40.616745),"[32, -3, 76, -31, -64, -52, 52, -61, 42, 9, 60...",14.042764
2,0.000314414156821,3,0.0843411059012,3,Allerton/Pelham Gardens,Bronx,"MULTIPOLYGON (((-73.84793 40.87134, -73.84725 ...",POINT (-73.847422 40.864474),"[-55, -76, -27, 34, 87, 1, 10, -50, -23, -15, ...",18.226086
3,0.000111871946192,4,0.0435665270921,4,Alphabet City,Manhattan,"MULTIPOLYGON (((-73.97177 40.72582, -73.97179 ...",POINT (-73.976968 40.723752),"[18, 31, -34, 77, 63, -71, 61, -11, -98, -51, ...",14.019641
4,0.000497957489363,5,0.0921464898574,5,Arden Heights,Staten Island,"MULTIPOLYGON (((-74.17422 40.56257, -74.17349 ...",POINT (-74.188484 40.552659),"[-90, 64, -87, -63, -55, -70, -21, -48, 61, -3...",12.281426
...,...,...,...,...,...,...,...,...,...,...
258,0.000168611097013,256,0.0679149669603,256,Williamsburg (South Side),Brooklyn,"MULTIPOLYGON (((-73.95834 40.71331, -73.95681 ...",POINT (-73.959905 40.71088),"[-75, 10, 69, 1, -29, 90, 41, 47, 55, 98, -34,...",10.357192
259,0.000394552487366,259,0.126750305191,259,Woodlawn/Wakefield,Bronx,"MULTIPOLYGON (((-73.85107 40.91037, -73.85207 ...",POINT (-73.852215 40.897932),"[-80, -15, -13, 18, 5, 17, 70, 41, -28, -49, -...",15.101268
260,0.000422345326907,260,0.133514154636,260,Woodside,Queens,"MULTIPOLYGON (((-73.90175 40.76078, -73.90147 ...",POINT (-73.906306 40.744235),"[46, 21, -42, -64, -49, -16, 60, 9, -51, -70, ...",18.545211
261,0.0000343423231652,261,0.0271204563616,261,World Trade Center,Manhattan,"MULTIPOLYGON (((-74.01333 40.70503, -74.01327 ...",POINT (-74.013023 40.709139),"[-81, -46, 13, 51, -76, -36, -95, 18, 72, -31,...",19.529951
262,0.000122330270966,262,0.0490636231541,262,Yorkville East,Manhattan,"MULTIPOLYGON (((-73.94383 40.78286, -73.94376 ...",POINT (-73.94651 40.775932),"[87, -90, -84, -80, 66, 33, -8, -90, 7, -23, 8...",11.474587

In [13]:
gdf.to_file('test.geojson',driver='GeoJSON')